[package]
name = "mycal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = { version = "4.3.5", features = ["derive"] }
kdam = "0.3.0"
porter-stemmer = "0.1.2"
rand = "0.8.5"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
flate2 = { version = "1.0.17", features = ["zlib-ng"], default-features = false }
sled = "0.34.7"
kv = { version = "0.24.0", features = ["bincode-value"] }
